version: '2.4'
services:
    artemis-app:
        platform: linux/x86_64
        image: ghcr.io/ls1intum/artemis
        build:
            context: ../../..
            dockerfile: src/main/docker/Dockerfile
        env_file: .env
        ports:
            - 8080:8080
        networks:
            - artemis
        depends_on:
            - artemis-mysql
    artemis-mysql:
        extends:
            file: mysql.yml
            service: artemis-mysql

networks:
    artemis:
        driver: "bridge"
